Class {
	#name : #CIComposedRuleTest,
	#superclass : #CIValidationRuleTest,
	#category : #'CI-Core-Test'
}

{ #category : #testing }
CIComposedRuleTest class >> isAbstract [
	^ self = CIComposedRuleTest
]

{ #category : #tests }
CIComposedRuleTest >> testLoadEmptyChange [
	"Don't care about this test in ComposedRule"
]

{ #category : #tests }
CIComposedRuleTest >> testLoadFailingChange [
	"Don't care about this test in ComposedRule"
]

{ #category : #tests }
CIComposedRuleTest >> testLoadSuccessfulChange [
	"Don't care about this test in ComposedRule"
]

{ #category : #tests }
CIComposedRuleTest >> testLoadWarningChange [
	"Don't care about this test in ComposedRule"
]
